// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCryptoInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1590362888;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'skyline_crypto_ffi',
    ioDirectory: '../../crypto-core/ffi/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiCryptoCryptoDeviceDecrypt(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber,
      required Envelope envelope});

  Future<Envelope> crateApiCryptoCryptoDeviceEncrypt(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber,
      required List<int> plaintext});

  Future<bool> crateApiCryptoCryptoDeviceHasSession(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber});

  Future<DeviceIdentity> crateApiCryptoCryptoDeviceIdentity(
      {required CryptoDevice that});

  Future<List<SignedPreKey>> crateApiCryptoCryptoDeviceNewKyberPreKeys(
      {required CryptoDevice that, required int count});

  Future<SignedPreKey> crateApiCryptoCryptoDeviceNewLastResortKyberPreKey(
      {required CryptoDevice that});

  Future<List<OneTimePreKey>> crateApiCryptoCryptoDeviceNewOneTimePreKeys(
      {required CryptoDevice that, required int count});

  Future<SignedPreKey> crateApiCryptoCryptoDeviceNewSignedPreKey(
      {required CryptoDevice that});

  Future<CryptoDevice> crateApiCryptoCryptoDeviceOpen(
      {required String path, required List<int> storageKey});

  Future<CryptoDevice> crateApiCryptoCryptoDeviceOpenInMemory();

  Future<SafetyNumber> crateApiCryptoCryptoDeviceSafetyNumber(
      {required CryptoDevice that,
      required String theirUserId,
      required int theirDeviceNumber,
      required List<int> theirIdentityKey});

  Future<void> crateApiCryptoCryptoDeviceSetLocalAddress(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber});

  Future<Uint8List> crateApiCryptoCryptoDeviceSign(
      {required CryptoDevice that, required List<int> message});

  Future<void> crateApiCryptoCryptoDeviceStartSession(
      {required CryptoDevice that,
      required String userId,
      required PreKeyBundle bundle});

  Future<void> crateApiCryptoInitApp();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CryptoDevice;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CryptoDevice;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CryptoDevicePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiCryptoCryptoDeviceDecrypt(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber,
      required Envelope envelope}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(userId, serializer);
        sse_encode_u_32(deviceNumber, serializer);
        sse_encode_box_autoadd_envelope(envelope, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceDecryptConstMeta,
      argValues: [that, userId, deviceNumber, envelope],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceDecryptConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_decrypt',
        argNames: ['that', 'userId', 'deviceNumber', 'envelope'],
      );

  @override
  Future<Envelope> crateApiCryptoCryptoDeviceEncrypt(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber,
      required List<int> plaintext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(userId, serializer);
        sse_encode_u_32(deviceNumber, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_envelope,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceEncryptConstMeta,
      argValues: [that, userId, deviceNumber, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceEncryptConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_encrypt',
        argNames: ['that', 'userId', 'deviceNumber', 'plaintext'],
      );

  @override
  Future<bool> crateApiCryptoCryptoDeviceHasSession(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(userId, serializer);
        sse_encode_u_32(deviceNumber, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceHasSessionConstMeta,
      argValues: [that, userId, deviceNumber],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceHasSessionConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_has_session',
        argNames: ['that', 'userId', 'deviceNumber'],
      );

  @override
  Future<DeviceIdentity> crateApiCryptoCryptoDeviceIdentity(
      {required CryptoDevice that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_identity,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceIdentityConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceIdentityConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_identity',
        argNames: ['that'],
      );

  @override
  Future<List<SignedPreKey>> crateApiCryptoCryptoDeviceNewKyberPreKeys(
      {required CryptoDevice that, required int count}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_u_32(count, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_signed_pre_key,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceNewKyberPreKeysConstMeta,
      argValues: [that, count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceNewKyberPreKeysConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_new_kyber_pre_keys',
        argNames: ['that', 'count'],
      );

  @override
  Future<SignedPreKey> crateApiCryptoCryptoDeviceNewLastResortKyberPreKey(
      {required CryptoDevice that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_signed_pre_key,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceNewLastResortKyberPreKeyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCryptoCryptoDeviceNewLastResortKyberPreKeyConstMeta =>
          const TaskConstMeta(
            debugName: 'CryptoDevice_new_last_resort_kyber_pre_key',
            argNames: ['that'],
          );

  @override
  Future<List<OneTimePreKey>> crateApiCryptoCryptoDeviceNewOneTimePreKeys(
      {required CryptoDevice that, required int count}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_u_32(count, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_one_time_pre_key,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceNewOneTimePreKeysConstMeta,
      argValues: [that, count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceNewOneTimePreKeysConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_new_one_time_pre_keys',
        argNames: ['that', 'count'],
      );

  @override
  Future<SignedPreKey> crateApiCryptoCryptoDeviceNewSignedPreKey(
      {required CryptoDevice that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_signed_pre_key,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceNewSignedPreKeyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceNewSignedPreKeyConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_new_signed_pre_key',
        argNames: ['that'],
      );

  @override
  Future<CryptoDevice> crateApiCryptoCryptoDeviceOpen(
      {required String path, required List<int> storageKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_list_prim_u_8_loose(storageKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceOpenConstMeta,
      argValues: [path, storageKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceOpenConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_open',
        argNames: ['path', 'storageKey'],
      );

  @override
  Future<CryptoDevice> crateApiCryptoCryptoDeviceOpenInMemory() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceOpenInMemoryConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceOpenInMemoryConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_open_in_memory',
        argNames: [],
      );

  @override
  Future<SafetyNumber> crateApiCryptoCryptoDeviceSafetyNumber(
      {required CryptoDevice that,
      required String theirUserId,
      required int theirDeviceNumber,
      required List<int> theirIdentityKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(theirUserId, serializer);
        sse_encode_u_32(theirDeviceNumber, serializer);
        sse_encode_list_prim_u_8_loose(theirIdentityKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_safety_number,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceSafetyNumberConstMeta,
      argValues: [that, theirUserId, theirDeviceNumber, theirIdentityKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceSafetyNumberConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_safety_number',
        argNames: [
          'that',
          'theirUserId',
          'theirDeviceNumber',
          'theirIdentityKey'
        ],
      );

  @override
  Future<void> crateApiCryptoCryptoDeviceSetLocalAddress(
      {required CryptoDevice that,
      required String userId,
      required int deviceNumber}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(userId, serializer);
        sse_encode_u_32(deviceNumber, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceSetLocalAddressConstMeta,
      argValues: [that, userId, deviceNumber],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceSetLocalAddressConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_set_local_address',
        argNames: ['that', 'userId', 'deviceNumber'],
      );

  @override
  Future<Uint8List> crateApiCryptoCryptoDeviceSign(
      {required CryptoDevice that, required List<int> message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_list_prim_u_8_loose(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceSignConstMeta,
      argValues: [that, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceSignConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_sign',
        argNames: ['that', 'message'],
      );

  @override
  Future<void> crateApiCryptoCryptoDeviceStartSession(
      {required CryptoDevice that,
      required String userId,
      required PreKeyBundle bundle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
            that, serializer);
        sse_encode_String(userId, serializer);
        sse_encode_box_autoadd_pre_key_bundle(bundle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_crypto_exception,
      ),
      constMeta: kCrateApiCryptoCryptoDeviceStartSessionConstMeta,
      argValues: [that, userId, bundle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoCryptoDeviceStartSessionConstMeta =>
      const TaskConstMeta(
        debugName: 'CryptoDevice_start_session',
        argNames: ['that', 'userId', 'bundle'],
      );

  @override
  Future<void> crateApiCryptoInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoInitAppConstMeta => const TaskConstMeta(
        debugName: 'init_app',
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CryptoDevice => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CryptoDevice => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice;

  @protected
  CryptoDevice
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoDevice
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoDevice
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Envelope dco_decode_box_autoadd_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_envelope(raw);
  }

  @protected
  OneTimePreKey dco_decode_box_autoadd_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_one_time_pre_key(raw);
  }

  @protected
  PreKeyBundle dco_decode_box_autoadd_pre_key_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pre_key_bundle(raw);
  }

  @protected
  CryptoErrorKind dco_decode_crypto_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoErrorKind.values[raw as int];
  }

  @protected
  CryptoException dco_decode_crypto_exception(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CryptoException(
      kind: dco_decode_crypto_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  DeviceIdentity dco_decode_device_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceIdentity(
      identityKey: dco_decode_list_prim_u_8_strict(arr[0]),
      registrationId: dco_decode_u_32(arr[1]),
      signingKey: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  Envelope dco_decode_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Envelope(
      kind: dco_decode_envelope_kind(arr[0]),
      body: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  EnvelopeKind dco_decode_envelope_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnvelopeKind.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<OneTimePreKey> dco_decode_list_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_one_time_pre_key).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SignedPreKey> dco_decode_list_signed_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_signed_pre_key).toList();
  }

  @protected
  OneTimePreKey dco_decode_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OneTimePreKey(
      keyId: dco_decode_u_32(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  OneTimePreKey? dco_decode_opt_box_autoadd_one_time_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_one_time_pre_key(raw);
  }

  @protected
  PreKeyBundle dco_decode_pre_key_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PreKeyBundle(
      registrationId: dco_decode_u_32(arr[0]),
      deviceNumber: dco_decode_u_32(arr[1]),
      identityKey: dco_decode_list_prim_u_8_strict(arr[2]),
      signedPreKey: dco_decode_signed_pre_key(arr[3]),
      kyberPreKey: dco_decode_signed_pre_key(arr[4]),
      preKey: dco_decode_opt_box_autoadd_one_time_pre_key(arr[5]),
    );
  }

  @protected
  SafetyNumber dco_decode_safety_number(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SafetyNumber(
      displayable: dco_decode_String(arr[0]),
      scannable: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SignedPreKey dco_decode_signed_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SignedPreKey(
      keyId: dco_decode_u_32(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
      signature: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CryptoDevice
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CryptoDevice
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CryptoDevice
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoDeviceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Envelope sse_decode_box_autoadd_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_envelope(deserializer));
  }

  @protected
  OneTimePreKey sse_decode_box_autoadd_one_time_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_one_time_pre_key(deserializer));
  }

  @protected
  PreKeyBundle sse_decode_box_autoadd_pre_key_bundle(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pre_key_bundle(deserializer));
  }

  @protected
  CryptoErrorKind sse_decode_crypto_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CryptoErrorKind.values[inner];
  }

  @protected
  CryptoException sse_decode_crypto_exception(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_crypto_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return CryptoException(kind: var_kind, message: var_message);
  }

  @protected
  DeviceIdentity sse_decode_device_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identityKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_registrationId = sse_decode_u_32(deserializer);
    var var_signingKey = sse_decode_list_prim_u_8_strict(deserializer);
    return DeviceIdentity(
        identityKey: var_identityKey,
        registrationId: var_registrationId,
        signingKey: var_signingKey);
  }

  @protected
  Envelope sse_decode_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_envelope_kind(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    return Envelope(kind: var_kind, body: var_body);
  }

  @protected
  EnvelopeKind sse_decode_envelope_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EnvelopeKind.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<OneTimePreKey> sse_decode_list_one_time_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OneTimePreKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_one_time_pre_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SignedPreKey> sse_decode_list_signed_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SignedPreKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_signed_pre_key(deserializer));
    }
    return ans_;
  }

  @protected
  OneTimePreKey sse_decode_one_time_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyId = sse_decode_u_32(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return OneTimePreKey(keyId: var_keyId, publicKey: var_publicKey);
  }

  @protected
  OneTimePreKey? sse_decode_opt_box_autoadd_one_time_pre_key(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_one_time_pre_key(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PreKeyBundle sse_decode_pre_key_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registrationId = sse_decode_u_32(deserializer);
    var var_deviceNumber = sse_decode_u_32(deserializer);
    var var_identityKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signedPreKey = sse_decode_signed_pre_key(deserializer);
    var var_kyberPreKey = sse_decode_signed_pre_key(deserializer);
    var var_preKey = sse_decode_opt_box_autoadd_one_time_pre_key(deserializer);
    return PreKeyBundle(
        registrationId: var_registrationId,
        deviceNumber: var_deviceNumber,
        identityKey: var_identityKey,
        signedPreKey: var_signedPreKey,
        kyberPreKey: var_kyberPreKey,
        preKey: var_preKey);
  }

  @protected
  SafetyNumber sse_decode_safety_number(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayable = sse_decode_String(deserializer);
    var var_scannable = sse_decode_list_prim_u_8_strict(deserializer);
    return SafetyNumber(displayable: var_displayable, scannable: var_scannable);
  }

  @protected
  SignedPreKey sse_decode_signed_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyId = sse_decode_u_32(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    return SignedPreKey(
        keyId: var_keyId, publicKey: var_publicKey, signature: var_signature);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoDeviceImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoDeviceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoDeviceImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_envelope(
      Envelope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_envelope(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_one_time_pre_key(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pre_key_bundle(
      PreKeyBundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pre_key_bundle(self, serializer);
  }

  @protected
  void sse_encode_crypto_error_kind(
      CryptoErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_crypto_exception(
      CryptoException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crypto_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_device_identity(
      DeviceIdentity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.identityKey, serializer);
    sse_encode_u_32(self.registrationId, serializer);
    sse_encode_list_prim_u_8_strict(self.signingKey, serializer);
  }

  @protected
  void sse_encode_envelope(Envelope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_envelope_kind(self.kind, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
  }

  @protected
  void sse_encode_envelope_kind(EnvelopeKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_one_time_pre_key(
      List<OneTimePreKey> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_one_time_pre_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_signed_pre_key(
      List<SignedPreKey> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_signed_pre_key(item, serializer);
    }
  }

  @protected
  void sse_encode_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.keyId, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_one_time_pre_key(
      OneTimePreKey? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_one_time_pre_key(self, serializer);
    }
  }

  @protected
  void sse_encode_pre_key_bundle(PreKeyBundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.registrationId, serializer);
    sse_encode_u_32(self.deviceNumber, serializer);
    sse_encode_list_prim_u_8_strict(self.identityKey, serializer);
    sse_encode_signed_pre_key(self.signedPreKey, serializer);
    sse_encode_signed_pre_key(self.kyberPreKey, serializer);
    sse_encode_opt_box_autoadd_one_time_pre_key(self.preKey, serializer);
  }

  @protected
  void sse_encode_safety_number(SafetyNumber self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayable, serializer);
    sse_encode_list_prim_u_8_strict(self.scannable, serializer);
  }

  @protected
  void sse_encode_signed_pre_key(SignedPreKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.keyId, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CryptoDeviceImpl extends RustOpaque implements CryptoDevice {
  // Not to be used by end users
  CryptoDeviceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CryptoDeviceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CryptoDevice,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CryptoDevice,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CryptoDevicePtr,
  );

  Future<Uint8List> decrypt(
          {required String userId,
          required int deviceNumber,
          required Envelope envelope}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceDecrypt(
          that: this,
          userId: userId,
          deviceNumber: deviceNumber,
          envelope: envelope);

  Future<Envelope> encrypt(
          {required String userId,
          required int deviceNumber,
          required List<int> plaintext}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceEncrypt(
          that: this,
          userId: userId,
          deviceNumber: deviceNumber,
          plaintext: plaintext);

  Future<bool> hasSession(
          {required String userId, required int deviceNumber}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceHasSession(
          that: this, userId: userId, deviceNumber: deviceNumber);

  Future<DeviceIdentity> identity() =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceIdentity(
        that: this,
      );

  Future<List<SignedPreKey>> newKyberPreKeys({required int count}) =>
      RustLib.instance.api
          .crateApiCryptoCryptoDeviceNewKyberPreKeys(that: this, count: count);

  Future<SignedPreKey> newLastResortKyberPreKey() =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceNewLastResortKyberPreKey(
        that: this,
      );

  Future<List<OneTimePreKey>> newOneTimePreKeys({required int count}) => RustLib
      .instance.api
      .crateApiCryptoCryptoDeviceNewOneTimePreKeys(that: this, count: count);

  Future<SignedPreKey> newSignedPreKey() =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceNewSignedPreKey(
        that: this,
      );

  Future<SafetyNumber> safetyNumber(
          {required String theirUserId,
          required int theirDeviceNumber,
          required List<int> theirIdentityKey}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceSafetyNumber(
          that: this,
          theirUserId: theirUserId,
          theirDeviceNumber: theirDeviceNumber,
          theirIdentityKey: theirIdentityKey);

  Future<void> setLocalAddress(
          {required String userId, required int deviceNumber}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceSetLocalAddress(
          that: this, userId: userId, deviceNumber: deviceNumber);

  Future<Uint8List> sign({required List<int> message}) => RustLib.instance.api
      .crateApiCryptoCryptoDeviceSign(that: this, message: message);

  Future<void> startSession(
          {required String userId, required PreKeyBundle bundle}) =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceStartSession(
          that: this, userId: userId, bundle: bundle);
}
