// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CryptoDevicePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevicePtr;

  @protected
  CryptoDevice
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw);

  @protected
  CryptoDevice
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw);

  @protected
  CryptoDevice
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Envelope dco_decode_box_autoadd_envelope(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  OneTimePreKey dco_decode_box_autoadd_one_time_pre_key(dynamic raw);

  @protected
  PreKeyBundle dco_decode_box_autoadd_pre_key_bundle(dynamic raw);

  @protected
  CryptoErrorKind dco_decode_crypto_error_kind(dynamic raw);

  @protected
  CryptoException dco_decode_crypto_exception(dynamic raw);

  @protected
  DeviceIdentity dco_decode_device_identity(dynamic raw);

  @protected
  Envelope dco_decode_envelope(dynamic raw);

  @protected
  EnvelopeKind dco_decode_envelope_kind(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<OneTimePreKey> dco_decode_list_one_time_pre_key(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SignedPreKey> dco_decode_list_signed_pre_key(dynamic raw);

  @protected
  List<StoredRecord> dco_decode_list_stored_record(dynamic raw);

  @protected
  OneTimePreKey dco_decode_one_time_pre_key(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  OneTimePreKey? dco_decode_opt_box_autoadd_one_time_pre_key(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PinCheck dco_decode_pin_check(dynamic raw);

  @protected
  PreKeyBundle dco_decode_pre_key_bundle(dynamic raw);

  @protected
  SafetyNumber dco_decode_safety_number(dynamic raw);

  @protected
  SignedPreKey dco_decode_signed_pre_key(dynamic raw);

  @protected
  StoredRecord dco_decode_stored_record(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  CryptoDevice
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer);

  @protected
  CryptoDevice
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer);

  @protected
  CryptoDevice
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Envelope sse_decode_box_autoadd_envelope(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OneTimePreKey sse_decode_box_autoadd_one_time_pre_key(
      SseDeserializer deserializer);

  @protected
  PreKeyBundle sse_decode_box_autoadd_pre_key_bundle(
      SseDeserializer deserializer);

  @protected
  CryptoErrorKind sse_decode_crypto_error_kind(SseDeserializer deserializer);

  @protected
  CryptoException sse_decode_crypto_exception(SseDeserializer deserializer);

  @protected
  DeviceIdentity sse_decode_device_identity(SseDeserializer deserializer);

  @protected
  Envelope sse_decode_envelope(SseDeserializer deserializer);

  @protected
  EnvelopeKind sse_decode_envelope_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<OneTimePreKey> sse_decode_list_one_time_pre_key(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SignedPreKey> sse_decode_list_signed_pre_key(
      SseDeserializer deserializer);

  @protected
  List<StoredRecord> sse_decode_list_stored_record(
      SseDeserializer deserializer);

  @protected
  OneTimePreKey sse_decode_one_time_pre_key(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OneTimePreKey? sse_decode_opt_box_autoadd_one_time_pre_key(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PinCheck sse_decode_pin_check(SseDeserializer deserializer);

  @protected
  PreKeyBundle sse_decode_pre_key_bundle(SseDeserializer deserializer);

  @protected
  SafetyNumber sse_decode_safety_number(SseDeserializer deserializer);

  @protected
  SignedPreKey sse_decode_signed_pre_key(SseDeserializer deserializer);

  @protected
  StoredRecord sse_decode_stored_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
          CryptoDevice self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_envelope(Envelope self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pre_key_bundle(
      PreKeyBundle self, SseSerializer serializer);

  @protected
  void sse_encode_crypto_error_kind(
      CryptoErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_crypto_exception(
      CryptoException self, SseSerializer serializer);

  @protected
  void sse_encode_device_identity(
      DeviceIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_envelope(Envelope self, SseSerializer serializer);

  @protected
  void sse_encode_envelope_kind(EnvelopeKind self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_one_time_pre_key(
      List<OneTimePreKey> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_signed_pre_key(
      List<SignedPreKey> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stored_record(
      List<StoredRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_one_time_pre_key(
      OneTimePreKey self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_one_time_pre_key(
      OneTimePreKey? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pin_check(PinCheck self, SseSerializer serializer);

  @protected
  void sse_encode_pre_key_bundle(PreKeyBundle self, SseSerializer serializer);

  @protected
  void sse_encode_safety_number(SafetyNumber self, SseSerializer serializer);

  @protected
  void sse_encode_signed_pre_key(SignedPreKey self, SseSerializer serializer);

  @protected
  void sse_encode_stored_record(StoredRecord self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_skyline_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_skyline_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevice =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoDevicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
