// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `signed`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoDevice>>
abstract class CryptoDevice implements RustOpaqueInterface {
  Future<PinCheck> checkAppLockPin({required String pin});

  Future<void> clearAppLockPin();

  /// `directory_identity_key`: the key directory's identity key for the
  /// sending device. Required for a first message from an unseen device.
  Future<Uint8List> decrypt(
      {required String userId,
      required int deviceNumber,
      required Envelope envelope,
      Uint8List? directoryIdentityKey});

  Future<bool> deleteRecord({required String kind, required String id});

  Future<int> deleteRecordGroup({required String kind, required String group});

  Future<Envelope> encrypt(
      {required String userId,
      required int deviceNumber,
      required List<int> plaintext});

  Future<Uint8List?> getRecord({required String kind, required String id});

  Future<bool> hasAppLockPin();

  Future<bool> hasSession({required String userId, required int deviceNumber});

  Future<DeviceIdentity> identity();

  Future<List<StoredRecord>> listRecords(
      {required String kind,
      required String group,
      PlatformInt64? beforeSort,
      required int limit});

  Future<List<SignedPreKey>> newKyberPreKeys({required int count});

  Future<SignedPreKey> newLastResortKyberPreKey();

  Future<List<OneTimePreKey>> newOneTimePreKeys({required int count});

  Future<SignedPreKey> newSignedPreKey();

  /// Opens (or on first use creates) the vault file. `storage_key` is 32
  /// bytes the app keeps in the OS keystore.
  static Future<CryptoDevice> open(
          {required String path, required List<int> storageKey}) =>
      RustLib.instance.api
          .crateApiCryptoCryptoDeviceOpen(path: path, storageKey: storageKey);

  /// A throwaway in-memory device (tests and diagnostics only).
  static Future<CryptoDevice> openInMemory() =>
      RustLib.instance.api.crateApiCryptoCryptoDeviceOpenInMemory();

  Future<void> putRecord(
      {required String kind,
      required String id,
      required String group,
      required PlatformInt64 sort,
      required List<int> value});

  Future<SafetyNumber> safetyNumber(
      {required String theirUserId,
      required int theirDeviceNumber,
      required List<int> theirIdentityKey});

  Future<void> setAppLockPin({required String pin});

  Future<void> setLocalAddress(
      {required String userId, required int deviceNumber});

  Future<Uint8List> sign({required List<int> message});

  Future<void> startSession(
      {required String userId, required PreKeyBundle bundle});

  Future<bool> verifyScannedSafetyNumber(
      {required String theirUserId,
      required int theirDeviceNumber,
      required List<int> theirIdentityKey,
      required List<int> scanned});
}

enum CryptoErrorKind {
  vaultLocked,
  storage,
  invalidInput,
  untrustedIdentity,
  noSession,
  noLocalAddress,
  protocol,
  ;
}

/// Thrown on the Dart side for every failure. `message` never contains key
/// material or plaintext.
class CryptoException implements FrbException {
  final CryptoErrorKind kind;
  final String message;

  const CryptoException({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CryptoException &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

class DeviceIdentity {
  final Uint8List identityKey;
  final int registrationId;
  final Uint8List signingKey;

  const DeviceIdentity({
    required this.identityKey,
    required this.registrationId,
    required this.signingKey,
  });

  @override
  int get hashCode =>
      identityKey.hashCode ^ registrationId.hashCode ^ signingKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceIdentity &&
          runtimeType == other.runtimeType &&
          identityKey == other.identityKey &&
          registrationId == other.registrationId &&
          signingKey == other.signingKey;
}

class Envelope {
  final EnvelopeKind kind;
  final Uint8List body;

  const Envelope({
    required this.kind,
    required this.body,
  });

  @override
  int get hashCode => kind.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Envelope &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          body == other.body;
}

enum EnvelopeKind {
  preKey,
  whisper,
  ;
}

class OneTimePreKey {
  final int keyId;
  final Uint8List publicKey;

  const OneTimePreKey({
    required this.keyId,
    required this.publicKey,
  });

  @override
  int get hashCode => keyId.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneTimePreKey &&
          runtimeType == other.runtimeType &&
          keyId == other.keyId &&
          publicKey == other.publicKey;
}

class PinCheck {
  final bool ok;
  final int waitSeconds;

  const PinCheck({
    required this.ok,
    required this.waitSeconds,
  });

  @override
  int get hashCode => ok.hashCode ^ waitSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinCheck &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          waitSeconds == other.waitSeconds;
}

class PreKeyBundle {
  final int registrationId;
  final int deviceNumber;
  final Uint8List identityKey;
  final SignedPreKey signedPreKey;
  final SignedPreKey kyberPreKey;
  final OneTimePreKey? preKey;

  const PreKeyBundle({
    required this.registrationId,
    required this.deviceNumber,
    required this.identityKey,
    required this.signedPreKey,
    required this.kyberPreKey,
    this.preKey,
  });

  @override
  int get hashCode =>
      registrationId.hashCode ^
      deviceNumber.hashCode ^
      identityKey.hashCode ^
      signedPreKey.hashCode ^
      kyberPreKey.hashCode ^
      preKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreKeyBundle &&
          runtimeType == other.runtimeType &&
          registrationId == other.registrationId &&
          deviceNumber == other.deviceNumber &&
          identityKey == other.identityKey &&
          signedPreKey == other.signedPreKey &&
          kyberPreKey == other.kyberPreKey &&
          preKey == other.preKey;
}

class SafetyNumber {
  final String displayable;
  final Uint8List scannable;

  const SafetyNumber({
    required this.displayable,
    required this.scannable,
  });

  @override
  int get hashCode => displayable.hashCode ^ scannable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyNumber &&
          runtimeType == other.runtimeType &&
          displayable == other.displayable &&
          scannable == other.scannable;
}

class SignedPreKey {
  final int keyId;
  final Uint8List publicKey;
  final Uint8List signature;

  const SignedPreKey({
    required this.keyId,
    required this.publicKey,
    required this.signature,
  });

  @override
  int get hashCode => keyId.hashCode ^ publicKey.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedPreKey &&
          runtimeType == other.runtimeType &&
          keyId == other.keyId &&
          publicKey == other.publicKey &&
          signature == other.signature;
}

class StoredRecord {
  final PlatformInt64 sort;
  final Uint8List value;

  const StoredRecord({
    required this.sort,
    required this.value,
  });

  @override
  int get hashCode => sort.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredRecord &&
          runtimeType == other.runtimeType &&
          sort == other.sort &&
          value == other.value;
}
